variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "aws_region" {}
variable "avail_zone" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "ami_id" {}
variable "instance_type" {}
variable "my_public_key" {}
variable "public_key_location" {}
